import nltk
import random
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

textao = [
    ("I love the game and just wish there was an easier to get revived, raid passes, potions more easier and the raids with big Pokemon a little easier especially for people who don't have many friends to play Pokemon go with or who have health issues where they can't physically get to the Poke stops or gyms and it would be a lot better if there was a way to actually talk in the game with other players", "pos")
    ("love it and it is amazing I can not do this on my phone cuz my parents took it One of the most fun and addicting games I have ever played. A whole new Pokemon experience and mechanics. There are a lot of bugs and problems, but I feel they will get updated soon since the app is in such an early state. Would love features like battling other trainers directly, trading, and being able to add friends.", "pos"),
    ("As immersive as you allow it to be. The framework of the game is very outdated, but it gets the job done. Still a lot to be desired (better achievement system would be a great start), but I'm afraid a new game would have to be created to get a much better experience. Addictive, gets you out, gets you walking/running, and there are people playing it almost everywhere if you want to socialize. Amazing game.", "pos"),
    ("Addicting in the best way, active, social, fun easy to play hard to stop playing", "pos"),
    ("This game was excellent. I've spent months playing this game, taking it along to parks, around the block, and on vacations just to find rare pokemon and get some progress on my pokedex. I've recently came back to the game, and my avatar was changed for the worse. The new customizations are atrocious. It killed off the game's original, great avatar style, just to replace it with the uncanny, broken mess we have today. Listen to your community and give an option to use the old style, good lord.", "pos"),
    ("Great game! If you want to meet new people in your town, this is one good way to do it! Developers, please fix the sound glitch. my sound disappears after only a few minutes of playing the game. Only restarting the game resets it temporarily.", "pos")
    ("Love it! I have had it since it first came out and im always amazed at what all they think of to keep things exciting. I wish the hype would come back, because when this first came out it was simply amazing to see so many people out and about with family and friends. At that time the servers couldn't handle it so it was very laggy and it was very simple game play. now it's better and has more to offer! I do wish some items were cheaper, like the remote raid passes.", "pos"),
    ("As a long time pokemon fan, the game really is fun and a great way to encourage exercise and exploration. However, it's got a lot of limitations that I wish I could see improvement on-- specifically, scheduling. Many events last only an hour, and all events are exclusively during the day. This may not be an issue for most people, but sadly I work the graveyard shift and sleep during the day, so if I want to participate in raids, community days, or highlight hours, I have to forgo sleep.", "neu"),
    ("Id say the game is still fun and playable. but that's as far as the good things go. The microtransactions are worse than ever, just reviving your Pokémon can be a struggle. its hard just to get together and play it anymore because there's constant issues with someone or everyone not having a raid pass, or having to buy a remote raid pass. its quite annoying and I loved this game when it first came out. I cant give it anything above 3 stars.", "neu"),
    ("I really enjoy Pokemon Go and have been playing since the release in 2016. Its a good excuse to get out and spend some time outside to touch grass. However, the Android app has significantly more issues than the iOS app does. I have to sign out and back in on average about 4 times per week and deal with freezes daily. This would be a 5 star review if the app was more flushed out, but given the issues I have seemingly just playing the game I can't give more than 3.", "neu")
    ("I love playing Pokémon Go! I have been playing since 2019 and have been off and on over the years. It pains me to drop a 3 star because I recently got into playing more battles, and let me tell you, I have never been more disappointed in a online matchmaking system in my entire life! Loss after Loss and it seems like every time I hop in a battle my opponent has too many counters. Now I know that fixing a matchmaking system is a lot of work, but for the love of God make it more rewarding to play.", "neu")
    ("Love the game, it's super cool, but the animations and whatnot for literally everything are SO LONG. Every evolution doesn't need a full 30 seconds, and opening gifts shouldn't need to show everything in it separately. A way to cut animation time or just get rid of it altogether would be nice, bc I feel like half the time I play this game I'm just mashing the screen trying to get it to hurry up and finish with whatever stupid animation is taking up my time.", "neu")
    ("I honestly enjoy the game. Having big issues with routes. I start right at the beginning of routes and follow the path directly as laid out and the game decides whenever I am doing anything other than idly on the map screen that I am no longer following the route. Please make it easier to follow routes or fix the detection its annoying constantly having to retrace steps to fix the issue.", "neu")
    ("i hate that it can not download on samson galaxy s3 i think they shout fix that", "neg"),
    ("just remote raided a honedge (because why not), got to the catch screen and the game said there was a network error and kicked me out. its combat power for the catch indicated it would've been a functional hundo. My internet status never changed and I was able to play the game fine right after. If this was an isolated event, it wouldn't be an issue, but various things happen consistently. Your time (and money) is better spent playing the mainline games.", "neg")
    ("It's come a loooooong way since it's glitchy & limited 1st gen days, but there's still a lot more work to be done. PVP needs a balancing overhaul, the events end too quickly with rewards that don't warrant the rushed effort, and prices have almost doubled on passes of all sorts. At this point, I only continue playing because of all the time & money I've dumped into this game over the years, and it's an extra way for me and my girlfriend to bond.", "neu")
    ("Certain features like routes are still INCREDIBLY buggy even after a long time. Which wouldn't be a problem is evolutions weren't locked behind it. I can not recommend this app at this stage because it doesn't feel like the devs adds even trying to fix the issue. And THAT is why I have it such a low score.", "neg"),
    ("Now the recent update/upgrade is so good that you have to click on a gift multiple times before it will let you open it. guess it wants to make sure you want your friends gift? the new layout also is sus and was not broken so they decided it needed to be fixed for their own amusement. add the lag, glitching and inability to smoothly transition from WiFi to cell data, this is the game for you! Don't do anything you want to keep going from WiFi to cell data. it will crash just about every tim.", "neg")
    ("The new update that took away the navigation bar has made it so much harder to play the game. The developer seems to have forgotten that newer phones don't have back buttons and you have to swipe from the edge to go back. With the new update, you can't swipe to go back, despite this being possible in previous versions. It ends up wasting Pokeballs if you try to use your phone's normal method to go back.", "neg")
    ("great concept of a game, ruined by the greed of this company. get the bare minimum and expect to pay for anything extra. wouldn't mind that so much if the actual game worked well but no, it's so inconsistent, you'd have better luck winning scratch offs from your local gas station then this game actually working correctly. might as well hand it over to Game Freak as the let's go games work better on my switch made 7 years ago then your horrible app does on the most modern of phones.", "neg")]

palavras = word_tokenize(textao)
palavras_pare = set(stopwords.words('english'))

random.shuffle
palavras_filtradas = [w for w in palavras if w.lower() not in palavras_pare]

print(' '.join(palavras_filtradas))